use_frameworks!

platform :ios, '9.0'

target 'YiVideoEditor_Example' do
  pod 'YiVideoEditor', :path => '../'
  pod 'LLSimpleCamera', '~> 3.0'

  target 'YiVideoEditor_Tests' do
    inherit! :search_paths

    
  end
end
